# Generated by Django 2.1.2 on 2018-12-04 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('algorithm_models', '0001_initial'),
        ('datasets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='模型任务名称')),
                ('type', models.CharField(max_length=255, verbose_name='模型任务类型')),
                ('schedule_rule', models.CharField(default='', max_length=255, verbose_name='模型任务规则')),
                ('dataset_generate_method', models.CharField(default='', max_length=255, verbose_name='任务数据集生成方法')),
                ('dataset_generate_rule', models.CharField(default='', max_length=255, verbose_name='任务数据集生成规则')),
                ('status', models.IntegerField(choices=[(1, 'enable'), (2, 'disable')], default=1, verbose_name='模型任务状态')),
                ('details', models.TextField(default='', verbose_name='模型任务详情')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='模型任务创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='模型任务修改时间')),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithm_models.ModelInstance')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTaskExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'enable'), (2, 'disable')], default=1, verbose_name='模型任务执行状态')),
                ('result', models.CharField(default='', max_length=255, verbose_name='模型任务执行结果')),
                ('started', models.DateTimeField(verbose_name='模型任务执行开始时间')),
                ('ended', models.DateTimeField(verbose_name='模型任务执行结束修改结束时间')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='模型任务执行创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='模型任务执行修改时间')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.Dataset')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
                ('train_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.ModelTask')),
            ],
        ),
    ]
