# Generated by Django 2.1.2 on 2018-12-04 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corpus', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='元数据名称')),
                ('code', models.CharField(max_length=255, verbose_name='元数据代码')),
                ('status', models.IntegerField(choices=[(1, 'enable'), (2, 'disable')], default=1, verbose_name='元数据状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='元数据创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='元数据修改时间')),
                ('corpusbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.CorpusBase')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
        ),
    ]
