# Generated by Django 2.1.2 on 2018-12-04 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='租户名称')),
                ('code', models.CharField(max_length=255, verbose_name='租户代码')),
                ('status', models.IntegerField(choices=[(1, 'enable'), (2, 'disable')], default=1, verbose_name='租户状态')),
                ('type', models.CharField(max_length=255, verbose_name='租户类型')),
                ('details', models.TextField(default='', verbose_name='租户详情')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='租户创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='租户修改时间')),
                ('owner', models.IntegerField(blank=True, default=0, verbose_name='创建人')),
                ('tenant', models.IntegerField(blank=True, default=0, verbose_name='租户')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, verbose_name='用户代码')),
                ('status', models.IntegerField(choices=[(1, 'enable'), (2, 'disable')], default=1, verbose_name='用户状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='用户创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='用户修改时间')),
                ('owner', models.IntegerField(blank=True, default=0, verbose_name='创建人')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
