# Generated by Django 2.1.2 on 2018-12-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.IntegerField(blank=True, default=0, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant',
            field=models.IntegerField(blank=True, default=0, verbose_name='租户'),
        ),
    ]
