"""
Django settings for cwtap project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '(%#b5v+nn7yf_@#62^xt%a4#1%s3cdn4&jgv!=pe*%d0y*zb@-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # API功能增强框架
    'drf_yasg',  # API页面框架
    'oauth2_provider',  # OAuth2用户认证框架
    'users.apps.UsersConfig',  # 用户和租户模块
    'area_of_jobs.apps.AreaOfJobsConfig',  # 机构领域模块
    'knowledge_graphs.apps.KnowledgeGraphsConfig',  # 知识图谱模块
    'corpus.apps.CorpusConfig',  # 语料模块
    'labels.apps.LabelsConfig',  # 标签模块
    'keywords.apps.KeywordsConfig',  # 词库模块
    'algorithm_models.apps.AlgorithmModelsConfig',  # 算法模型模块
    'tasks.apps.TasksConfig',  # 任务模块
    'metas.apps.MetasConfig',  # 元数据模块
    'datasets.apps.DatasetsConfig',  # 数据集模块
    'rules.apps.RulesConfig'  # 规则模块

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cwtap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cwtap.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

pv_base = "django.contrib.auth.password_validation"

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': '{0}.{1}'.format(pv_base, 'UserAttributeSimilarityValidator')},
    {'NAME': '{0}.{1}'.format(pv_base, 'MinimumLengthValidator')},
    {'NAME': '{0}.{1}'.format(pv_base, 'CommonPasswordValidator')},
    {'NAME': '{0}.{1}'.format(pv_base, 'NumericPasswordValidator')},
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# 状态代码
STATUS_ENABLE = 1  # 启用
STATUS_DISABLE = 2  # 禁用

STATUS_CHOICES = (
    (STATUS_ENABLE, "enable"),
    (STATUS_DISABLE, "disable")
)

# 查询时间范围字段
QUERY_DATETIME_FIELDS = ["created", "modified"]
QUERY_DATETIME_DELIMITER = "to"

# 用户认证
CLIENT_ID = "WJ6rAkO4r0iKWtsm2dtmFVySlxHccIt90M47uWO4"
CLIENT_SECRET = "pe843MRWfCylspXhveCygCMuzAcInpQboQf6a8PRp03Bg7DMTZQe"
