# Generated by Django 2.1.2 on 2018-12-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordbase',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='是否为通用词库'),
        ),
        migrations.AddField(
            model_name='keywordbase',
            name='storage_location',
            field=models.CharField(default='', max_length=255, verbose_name='存储位置'),
        ),
        migrations.AlterField(
            model_name='keywordbase',
            name='type',
            field=models.IntegerField(choices=[(1, 'business'), (2, 'stop'), (3, 'cell'), (4, 'emotion'), (5, 'extreme'), (6, 'correct'), (7, 'uncorrect'), (8, 'synonym'), (9, 'antonym')], default=1, verbose_name='词库类型'),
        ),
    ]
