# Generated by Django 2.1.2 on 2018-12-04 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('area_of_jobs', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originate_object', models.CharField(default='', max_length=255, verbose_name='知识图谱来源')),
                ('originate_object_id', models.IntegerField(default='', verbose_name='知识图谱来源编号')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeGraphBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='知识图谱库名称')),
                ('code', models.CharField(max_length=255, verbose_name='知识图谱库代码')),
                ('details', models.TextField(default='', verbose_name='知识图谱库详情')),
                ('status', models.IntegerField(choices=[(1, 'enable'), (2, 'disable')], default=1, verbose_name='知识图谱库状态')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='知识图谱库创建时间')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='知识图谱库修改时间')),
                ('area_of_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area_of_jobs.AreaOfJob')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='knowledgebase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graphs.KnowledgeGraphBase'),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgegraph',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
    ]
